/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               /home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
bnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_invmass_spectrum.dat.lock'
srun: error: cn008: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 140, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_evis_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
                                                                                                                                                                                   /home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarnws/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
ts/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_costheta_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn011: task 0: Exited with exit code 1
srun: error: cn011: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 140, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_evis_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn011: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
ert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 148, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_costheta_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn013: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 140, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_evis_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 140, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_evis_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 148, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_costheta_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn013: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 140, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_evis_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 156, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_invmass_spectrum.dat.lock'
srun: error: cn013: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn009: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 156, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_invmass_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn009: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
srun: error: cn012: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
                                                                                                                                                                                                                                                                                         /home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
ost recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
Traceback (most rec/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
alysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 148, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_costheta_spectrum.dat.lock'
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 140, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_evis_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 156, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_invmass_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 156, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_invmass_spectrum.dat.lock'
srun: error: cn068: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn068: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_enu_spectrum.dat.lock'
srun: error: cn068: task 0: Exited with exit code 1
srun: error: cn068: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
ert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 156, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastTraceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 140, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
                                                                                                                                           srun: error: cn030: task 0: Exited with exit code 1
srun: error: cn030: task 0: Exited with exit code 1
srun: error: cn030: task 0: Exited with exit code 1
                                                    srun: error: cn030: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_enu_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn048: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn048: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
                                                                                                                    /home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 127, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_chi2.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 183, in <module>
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.015_eps_0.0008/5m_16d_1h_22m_16s_enu_spectrum.dat.lock'
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
srun: error: cn025: task 0: Exited with exit code 1
srun: error: cn025: task 0: Exited with exit code 1
srun: error: cn025: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:213: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
